name: 'clean-workspace-github-action'
description: 'This action cleans the workspace.'
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"
