name: Test

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Test:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          workspace: ${{ github.workspace }}
